name: Deploy Laravel to AWS Lambda Container

on:
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Use NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Serverless Framework
        run: npm i -g serverless@2.72.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install Bref for Serverless
        uses: php-actions/composer@v6
        with:
          # Install Bref for Serverless
          commands: require bref/bref bref/laravel-bridge --update-with-dependencies

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          args: --prefer-dist --optimize-autoloader

      - name: Setup app env
        run: |
          APP_VERSION=$(git describe --tags --abbrev=0) \
          APP_VERSION_HASH=$(git rev-parse --short $APP_VERSION) \
          echo "\nAPP_VERSION=${APP_VERSION}" >> .env \
          echo "APP_VERSION_HASH=${APP_VERSION_HASH}" >> .env
          
      - name: Verbose env file
        run: cat .env

      - name: Deploy App
        run: sls deploy --verbose
